[2023-10-29T02:30:49.065+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2023-10-29T02:30:27.833018+00:00 [queued]>
[2023-10-29T02:30:49.073+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2023-10-29T02:30:27.833018+00:00 [queued]>
[2023-10-29T02:30:49.073+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-10-29T02:30:49.088+0000] {taskinstance.py:1382} INFO - Executing <Task(S3ToRedshiftOperator): tsk_transfer_s3_to_redshift> on 2023-10-29 02:30:27.833018+00:00
[2023-10-29T02:30:49.091+0000] {standard_task_runner.py:57} INFO - Started process 1611 to run task
[2023-10-29T02:30:49.094+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_transfer_s3_to_redshift', 'manual__2023-10-29T02:30:27.833018+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/analytics.py', '--cfg-path', '/tmp/tmpi3m3s5hf']
[2023-10-29T02:30:49.095+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask tsk_transfer_s3_to_redshift
[2023-10-29T02:30:49.134+0000] {task_command.py:416} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2023-10-29T02:30:27.833018+00:00 [running]> on host ip-172-31-56-104.ec2.internal
[2023-10-29T02:30:49.198+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chattisowmya@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_transfer_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T02:30:27.833018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-29T02:30:27.833018+00:00'
[2023-10-29T02:30:49.202+0000] {base.py:73} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2023-10-29T02:30:49.205+0000] {base.py:73} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2023-10-29T02:30:49.205+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-10-29T02:30:49.216+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2023-10-29T02:30:49.223+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 196, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 173, in get_conn
    conn_params = self._get_conn_params()
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 79, in _get_conn_params
    conn = self.conn
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 75, in conn
    return self.get_connection(self.redshift_conn_id)  # type: ignore[attr-defined]
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/ubuntu/env/lib/python3.10/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `conn_id_redshift` isn't defined
[2023-10-29T02:30:49.240+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=zillow_analytics_dag, task_id=tsk_transfer_s3_to_redshift, execution_date=20231029T023027, start_date=20231029T023049, end_date=20231029T023049
[2023-10-29T02:30:49.252+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task tsk_transfer_s3_to_redshift (The conn_id `conn_id_redshift` isn't defined; 1611)
[2023-10-29T02:30:49.266+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-29T02:30:49.279+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
