[2023-10-29T02:11:07.174+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2023-10-29T02:10:41.332624+00:00 [queued]>
[2023-10-29T02:11:07.181+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2023-10-29T02:10:41.332624+00:00 [queued]>
[2023-10-29T02:11:07.181+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-10-29T02:11:07.200+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2023-10-29 02:10:41.332624+00:00
[2023-10-29T02:11:07.203+0000] {standard_task_runner.py:57} INFO - Started process 7321 to run task
[2023-10-29T02:11:07.206+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2023-10-29T02:10:41.332624+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/analytics.py', '--cfg-path', '/tmp/tmpo18h9y84']
[2023-10-29T02:11:07.208+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask tsk_is_file_in_s3_available
[2023-10-29T02:11:07.243+0000] {task_command.py:416} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2023-10-29T02:10:41.332624+00:00 [running]> on host ip-172-31-56-104.ec2.internal
[2023-10-29T02:11:07.304+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chattisowmya@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T02:10:41.332624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-29T02:10:41.332624+00:00'
[2023-10-29T02:11:07.304+0000] {s3.py:106} INFO - Poking for key : s3://cleaned-data-zone-for-csv-bucket/response_data_29102023021046.csv
[2023-10-29T02:11:07.308+0000] {base_aws.py:559} WARNING - Unable to find AWS Connection ID 'aws_s3_conn', switching to empty.
[2023-10-29T02:11:07.309+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2023-10-29T02:11:07.475+0000] {credentials.py:1052} INFO - Found credentials from IAM Role: EC2S3
[2023-10-29T02:11:07.657+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-29T02:11:07.662+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, execution_date=20231029T021041, start_date=20231029T021107, end_date=20231029T021107
[2023-10-29T02:11:07.699+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-29T02:11:07.720+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
